networks: 
  main: 
    driver: bridge
    ipam: 
      config: 
        - subnet: 10.0.0.0/24
      driver: default
services: 
  nats-1: 
    command: 
      - "-D"
      - "-p"
      - "4222"
      - "-cluster"
      - "nats://10.0.0.10:6222"
    image: "nats:1.3.0"
    networks: 
      main: 
        ipv4_address: "10.0.0.10"
    ports:
      - "14222:4222"
  nats-2: 
    command: 
      - "-D"
      - "-p"
      - "4222"
      - "-cluster"
      - "nats://10.0.0.20:6222"
      - "-routes"
      - "nats://10.0.0.10:6222"
    image: "nats:1.3.0"
    networks: 
      main: 
        ipv4_address: "10.0.0.20"
    ports:
      - "24222:4222"
  nats-3: 
    command: 
      - "-D"
      - "-p"
      - "4222"
      - "-cluster"
      - "nats://10.0.0.30:6222"
      - "-routes"
      - "nats://10.0.0.10:6222"
    image: "nats:1.3.0"
    networks: 
      main: 
        ipv4_address: "10.0.0.30"
    ports:
      - "34222:4222"
  nats-streaming-1:
    image: "nats-streaming"
    networks: 
      main: 
        ipv4_address: "10.0.0.40"
    command: -ns nats://10.0.0.10:4222 -cid drone-simulation-cluster
    ports:
      - "4222"
      - "8222"
    depends_on:
      - nats-1
  
  nats-processor-position-update-1:
    image: "pietersynthesis/nats-swarm-positionupdate:x86"
    networks: 
      - main
    depends_on:
      - nats-streaming-1

  nats-processor-position-update-2:
    image: "pietersynthesis/nats-swarm-positionupdate:x86"
    networks: 
      - main
    depends_on:
      - nats-streaming-1

  nats-processor-position-update-3:
    image: "pietersynthesis/nats-swarm-positionupdate:x86"
    networks: 
      - main
    depends_on:
      - nats-streaming-1

  nats-processor-distance-calc-1:
    image: "pietersynthesis/nats-swarm-distancecalculator:x86"
    networks: 
      - main
    depends_on:
      - nats-streaming-1

  # nats-processor-distance-calc-2:
  #   image: "pietersynthesis/nats-swarm-distancecalculator:x86"
  #   networks: 
  #     - main
  #   depends_on:
  #     - nats-streaming-1


  nats-processor-distance-trigger-1:
    image: "pietersynthesis/nats-swarm-distancetrigger:x86"
    networks: 
      - main
    depends_on:
      - nats-streaming-1
  # nats-processor-distance-trigger-2:
  #   image: "pietersynthesis/nats-swarm-distancetrigger:x86"
  #   networks: 
  #     - main
  #   depends_on:
  #     - nats-streaming-1

  nats-processor-deadnode-detector-1:
    image: "pietersynthesis/nats-swarm-deadnodedetector:x86"
    networks: 
      - main
    depends_on:
      - nats-streaming-1

version: "3.3"